(() => {
  const requested = new URLSearchParams(location.search).get('lang');
  const language = requested === 'en' || requested === 'ko' ? requested : (localStorage.getItem('rootlinkLanguage') || 'ko');
  const switcher = document.querySelector('#langSwitch');
  switcher.textContent = language === 'en' ? 'KO' : 'EN';
  switcher.setAttribute('aria-label', language === 'en' ? '한국어로 전환' : 'Switch to English');
  const next = language === 'en' ? 'ko' : 'en';
  switcher.href = `?lang=${next}`;
  switcher.onclick = () => localStorage.setItem('rootlinkLanguage', next);
  if (language !== 'en') return;

  document.documentElement.lang = 'en';
  document.title = 'RootLink — Culture travels with you';
  const pairs = [
    ['성인 모드','Adult mode'],['체험 로그인','Demo login'],['고향의 문화를 안전하게 기록하고, 새로운 공동체와 연결합니다. 한 지역의 이야기가 웹사이트를 통해 다른 지역의 로봇과 사람들에게 전달됩니다.','Safely preserve the culture of home and connect with a new community. Stories from one place travel through the web to robots and people in another.'],['문화 기록하기 →','Record your culture →'],['문화 배우기','Learn about culture'],['우리 가족의 봄 명절 음식','Our family’s spring holiday dish'],
    ['연결된 문화 지역','Cultural regions connected'],['기록된 문화 이야기','Cultural stories recorded'],['연결된 RootLink','RootLinks connected'],['콘텐츠 전송 성공률','Successful content transfers'],['성인을 위한 생활문화 학습','Everyday culture for adults'],['학교, 병원, 교통 등 새로운 지역에서 필요한 정보를 알아보세요.','Learn what you need in a new community—from schools and hospitals to transportation.'],['추천 학습 보기','View recommended lessons'],['오늘 도착한 문화 이야기','Cultural stories arriving today'],['각 이야기에는 한 가족과 지역의 고유한 경험이 담겨 있습니다.','Every story holds the unique experience of a family and its community.'],['모두 둘러보기 →','Explore all →'],
    ['“하나의 이야기를\n한 국가 전체의 문화로\n일반화하지 않습니다.”','“One story does not\nrepresent the culture\nof an entire country.”'],['안전하게 기록하고, 존중하며 공유합니다.','Record safely. Share respectfully.'],['모든 콘텐츠는 촬영자의 동의와 공개 범위를 먼저 확인합니다. 미성년자의 영상은 기본적으로 비공개이며, 얼굴 가림과 삭제 요청을 언제든 지원합니다.','Every story is checked for consent and sharing permissions first. Videos of minors are private by default, with face blurring and deletion requests supported at any time.'],['🔒 공개 범위 선택','🔒 Choose who can view'],['👤 별명 사용','👤 Use a nickname'],['🛡 보호자 동의','🛡 Guardian consent'],['✦ 검토 완료 표시','✦ Reviewed badge'],
    ['서로의 이야기를 만나요','Discover each other’s stories'],['국가가 아닌 지역과 가족의 경험으로 문화를 탐색합니다.','Explore culture through the experiences of communities and families—not national stereotypes.'],['전체','All'],['음식','Food'],['명절','Holidays'],['놀이','Play'],['음악','Music'],['생활예절','Everyday customs'],['ⓘ 같은 국가 안에서도 지역과 가족에 따라 문화가 다를 수 있습니다.','ⓘ Culture can differ by community and family, even within the same country.'],
    ['당신의 문화를 기록해 주세요','Record your culture'],['로봇에서 촬영한 영상이나 음성을 불러와 안전하게 보관할 수 있습니다.','Import video or audio captured by a robot and keep it safely on this device.'],['새 문화 이야기','New cultural story'],['문화 제목','Story title'],['국가','Country'],['지역','Region'],['사용 언어','Language used'],['문화 분야','Culture category'],['영상 또는 음성','Video or audio'],['＋ 파일을 선택하거나 여기에 놓으세요','＋ Choose a file or drop it here'],['MP4, MOV, MP3 · 최대 500MB','MP4, MOV, MP3 · up to 500MB'],['이야기 설명','Story description'],['공개 범위','Who can view'],['나와 가족만','Only me and my family'],['특정 공동체','Selected community'],['교육기관','Educational institutions'],['모든 사용자','All users'],['⚠ 다른 사람의 얼굴이나 개인정보가 포함되어 있다면 반드시 동의를 받아야 합니다.','⚠ You must get consent if another person’s face or personal information is included.'],['촬영 및 저장에 필요한 동의를 받았습니다.','I have the consent required to record and save this content.'],['임시 보관함에 저장 →','Save to drafts →'],
    ['등록 과정','How it works'],['문화 기록','Record culture'],['영상 또는 음성을 추가합니다.','Add video or audio.'],['정보와 동의 확인','Confirm details and consent'],['지역, 언어, 공개 범위를 정합니다.','Set the region, language, and audience.'],['안전 검토','Safety review'],['개인정보와 표현 방식을 확인합니다.','Check personal information and wording.'],['문화 연결','Connect cultures'],['승인 후 다른 RootLink로 전송합니다.','After approval, send it to another RootLink.'],
    ['문화 이야기를 안전하게 연결합니다','Connect cultural stories safely'],['문화의 진위를 판정하지 않고, 개인정보·동의·출처·표현 방식을 검토합니다.','We do not judge whether a culture is “authentic.” We review privacy, consent, sources, and wording.'],['원칙: 특정 가족의 경험임을 분명히 표시하고, 하나의 콘텐츠를 국가 전체의 문화로 일반화하지 않습니다.','Principle: Clearly identify each story as one family’s experience. Never generalize a single story to an entire country.'],['검토 대기','Awaiting review'],['시리아 · 알레포 · 아랍어 · 가족 문화 기록','Syria · Aleppo · Arabic · Family cultural record'],['검토 시작','Start review'],['안전 및 공개 체크리스트','Safety and sharing checklist'],['촬영자 동의를 확인했습니다.','The creator’s consent is confirmed.'],['이름과 연락처가 노출되지 않았습니다.','Names and contact details are not exposed.'],['특정 가족의 경험임이 표시되었습니다.','It is identified as one family’s experience.'],['자막이 원래 의미를 유지합니다.','The subtitles preserve the original meaning.'],['승인하고 전송 준비','Approve and prepare to send'],['수정 요청','Request changes'],['검토 완료','Reviewed'],['할머니가 불러주신 자장가','The lullaby Grandma sang'],['우크라이나 · 리비우 · 우크라이나어 · 가족 전용','Ukraine · Lviv · Ukrainian · Family only'],['검토 기록','Review history'],
    ['문화가 이동하는 네트워크','The network where culture travels'],['각 지역의 RootLink 상태를 확인하고 승인된 이야기를 전송합니다.','Check each RootLink’s status and send approved stories.'],['● 온라인','● Online'],['● 전송 대기','● Waiting to transfer'],['서울 문화센터','Seoul Cultural Center'],['부산 해솔초등학교','Busan Haesol Elementary School'],['독일 베를린 난민센터','Berlin Refugee Center, Germany'],['현재 작업','Current activity'],['영상 촬영','Recording video'],['문화 수업','Culture class'],['동기화 대기','Waiting to sync'],['배터리','Battery'],['충전 중','Charging'],['마지막 동기화','Last sync'],['방금 전','Just now'],['2분 전','2 minutes ago'],['1시간 전','1 hour ago'],['콘텐츠','Content'],['38개','38 items'],['52개','52 items'],['27개','27 items'],['🍲 우리 가족의 봄 명절 음식','🍲 Our family’s spring holiday dish'],['전송 준비 완료','Ready to transfer'],['이야기 전송하기','Send story'],
    ['뿌리를 기억하고, 서로를 배워요','Remember your roots. Learn from one another.'],['나이와 상황에 맞춘 문화 콘텐츠로 배움과 대화를 시작합니다.','Start learning and conversation with cultural content suited to every age and situation.'],['우리 가족의 영상, 고향 언어, 음식과 명절을 만나며 나의 뿌리를 배웁니다.','Discover your roots through family videos, hometown languages, food, and holidays.'],['고향 이야기 보기','Explore stories from home'],['학교, 병원, 교통과 공공기관 등 새로운 공동체의 생활문화를 배웁니다.','Learn everyday life in a new community, including schools, hospitals, transportation, and public services.'],['생활문화 배우기','Learn everyday culture'],['인사법, 음식과 이름을 소재로 난민과 현지 주민이 서로의 문화를 나눕니다.','Refugees and local residents share culture through greetings, food, and names.'],['함께 시작하기','Start together'],['영상 속 가족은 봄 명절에 어떤 음식을 함께 만들었나요?','What food did the family in the video make together for the spring holiday?'],['빵','Bread'],['향신료를 넣은 수프','Spiced soup'],['과일 주스','Fruit juice'],
    ['자율주행 로봇과 웹 기반 문화 네트워크가 결합된 양방향 문화교육 시스템','A two-way cultural learning system connecting autonomous robots with a web-based culture network'],['개인정보 원칙','Privacy principles'],['문화 일반화 방지','Avoiding cultural generalization'],['프로젝트 소개','About the project'],['문의','Contact'],['누가 RootLink를 사용하나요?','Who is using RootLink?'],['사용자에게 가장 편안한 화면과 콘텐츠를 보여드릴게요.','We’ll tailor the screen and content to make RootLink comfortable for you.'],['어린이','Child'],['큰 그림, 쉬운 말과 문화 게임','Large visuals, simple words, and culture games'],['청소년','Teen'],['고향 이야기와 새로운 친구 만나기','Stories from home and new friends'],['성인','Adult'],['생활정보와 정착국 문화 학습','Everyday information and local culture'],['부모','Parent'],['자녀 교육과 가족 문화 기록','Children’s learning and family culture records'],['노인','Senior'],['큰 글씨와 간단한 메뉴, 음성 중심','Large text, simple menus, and audio'],['현지 주민','Local resident'],['이웃의 문화와 교류 활동','Neighbors’ cultures and community activities'],
    ['이 기기의 임시 보관함','Drafts on this device'],['저장된 문화 이야기가 없습니다.','No cultural stories have been saved.'],['검토 예시','Review example'],['기기 저장 완료','Saved on device'],['지역 미입력','Region not entered'],['재생하기','Play'],['닫기','Close'],['삭제','Delete'],['이 브라우저에서 보관함을 열 수 없습니다.','Drafts cannot be opened in this browser.'],['파일을 선택해 주세요','Please choose a file'],['기기에 저장 중…','Saving to device…'],['전송 중…','Transferring…'],['전송 완료 ✓','Transfer complete ✓'],['새로운 문화 이야기가 도착했습니다!','A new cultural story has arrived!'],
    ['어린이 모드','Child mode'],['청소년 모드','Teen mode'],['부모 모드','Parent mode'],['노인 모드','Senior mode'],['현지 주민 모드','Local resident mode'],['그림으로 만나는 우리 가족 이야기','Our family stories in pictures'],['나의 뿌리와 새로운 친구들','My roots and new friends'],['가족의 기억을 안전하게 기록하세요','Preserve your family memories safely'],['가족에게 고향 이야기를 들려주세요','Share stories of home with your family'],['새로운 이웃의 문화를 만나보세요','Discover the cultures of new neighbors'],
    ['짧은 영상을 보고 재미있는 문화 퀴즈를 풀어보세요.','Watch short videos and try fun culture quizzes.'],['고향의 문화를 발견하고 또래 친구들의 이야기를 만나보세요.','Discover the culture of home and stories from people your age.'],['자녀와 함께 고향 이야기를 남기고 생활·교육 정보를 확인하세요.','Preserve stories of home with your children and find everyday and educational information.'],['큰 글씨와 간단한 버튼으로 녹화하고 가족 영상을 볼 수 있어요.','Use large text and simple buttons to record and watch family videos.'],['이름과 언어를 존중하며 명절, 음식, 인사법을 함께 배워요.','Learn about holidays, food, and greetings while respecting names and languages.'],
    ['✓ 검토 완료','✓ Reviewed'],['음식 · 가족 이야기','Food · Family story'],['음악 · 가족 이야기','Music · Family story'],['놀이 · 어린이','Play · Children'],['생활예절 · 인사','Everyday customs · Greetings'],['의상 · 손기술','Clothing · Handcraft'],['명절 · 가족 이야기','Holiday · Family story'],['시리아 · 알레포','Syria · Aleppo'],['우크라이나 · 리비우','Ukraine · Lviv'],['아프가니스탄 · 헤라트','Afghanistan · Herat'],['대한민국 · 부산','South Korea · Busan'],['시리아 · 다마스쿠스','Syria · Damascus'],['대한민국 · 전주','South Korea · Jeonju'],['바람 부는 날의 우리 동네 놀이','Our neighborhood game for a windy day'],['우리 동네의 따뜻한 인사법','Our neighborhood’s warm greeting'],['엄마에게 배운 전통 자수','Traditional embroidery I learned from Mom'],['새해에 서로 나누는 덕담','Good wishes we share for the new year'],['아랍어 / 한국어 자막 · 3분 24초','Arabic / Korean subtitles · 3m 24s'],['우크라이나어 / 한국어 자막 · 2분 10초','Ukrainian / Korean subtitles · 2m 10s'],['다리어 / 한국어 자막 · 4분 02초','Dari / Korean subtitles · 4m 02s'],['한국어 / 아랍어 자막 · 1분 48초','Korean / Arabic subtitles · 1m 48s'],['아랍어 / 영어 자막 · 5분 12초','Arabic / English subtitles · 5m 12s'],['한국어 / 영어 자막 · 2분 35초','Korean / English subtitles · 2m 35s'],['“하나의 이야기를','“One story does not'],['한 국가 전체의 문화로','represent the culture'],['일반화하지 않습니다.”','of an entire country.”']
  ];
  const dictionary = new Map(pairs);
  const translateText = value => dictionary.get(value.trim());
  function translate(root) {
    if (root.nodeType === Node.TEXT_NODE) {
      const translated = translateText(root.nodeValue);
      if (translated) root.nodeValue = root.nodeValue.replace(root.nodeValue.trim(), translated);
      return;
    }
    if (root.nodeType !== Node.ELEMENT_NODE) return;
    root.querySelectorAll('[placeholder]').forEach(el => { const text = dictionary.get(el.placeholder); if (text) el.placeholder = text; });
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let node;
    while ((node = walker.nextNode())) translate(node);
  }
  dictionary.set('예: 우리 가족의 봄 명절 음식','e.g. Our family’s spring holiday dish');
  dictionary.set('예: 알레포','e.g. Aleppo');
  dictionary.set('이 문화가 우리 가족에게 어떤 의미인지 알려주세요.','Tell us what this culture means to your family.');
  dictionary.set('나의 고향 이야기','My story from home'); dictionary.set('My Roots 문화 영상','My Roots cultural video'); dictionary.set('이 브라우저에서는 영상을 재생할 수 없습니다.','This browser cannot play the video.');
  dictionary.set('시리아','Syria'); dictionary.set('대한민국','South Korea'); dictionary.set('우크라이나','Ukraine'); dictionary.set('아프가니스탄','Afghanistan');
  dictionary.set('아랍어','Arabic'); dictionary.set('한국어','Korean'); dictionary.set('우크라이나어','Ukrainian'); dictionary.set('영어','English'); dictionary.set('가족 이야기','Family story');
  dictionary.set('육전, 삼색전','Yukjeon and three-color jeon');
  dictionary.set('카드 인식','Scan card'); dictionary.set('문화 카드 인식','Cultural card scanner');
  dictionary.set('▣ 문화 학습 카드 인식','▣ Scan learning card'); dictionary.set('문화 학습 카드 인식','Cultural learning card scanner');
  dictionary.set('음식·의상·음악 카드의 글자를 읽고 관련 학습 자료를 보여줍니다.','Read a food, clothing, or music card to see related learning material.');
  dictionary.set('BIBIMBAP·HANBOK·GUGAK 영어 카드를 보여주세요.','Show a card labeled BIBIMBAP, HANBOK, or GUGAK.');
  dictionary.set('H(한복)·I(비빔밥)·U(국악) 카드를 보여주세요.','Show an H (Hanbok), I (Bibimbap), or U (Gugak) card.');
  dictionary.set('다양한 음식 문화','Various food cultures');
  dictionary.set('F(음식)·H(한복)·I(비빔밥)·U(국악) 카드를 보여주세요.','Show an F (Food), H (Hanbok), I (Bibimbap), or U (Gugak) card.');
  dictionary.set('문화 학습 카드 인식 완료','Cultural learning card recognized');
  dictionary.set('사용자가 화면에서 ‘문화 기록하기’를 선택하면 RootLink는 촬영 동의와 공개 범위를 확인한 뒤 Culture Record 모드로 전환합니다.','When the user selects Record Culture on the screen, RootLink confirms recording consent and the sharing scope, then enters Culture Record mode.');
  dictionary.set('비빔밥·한복·국악 글자가 적힌 카드를 카메라에 보여주세요.','Show a card labeled Bibimbap, Hanbok, or Gugak to the camera.');
  dictionary.set('글자를 이 안에 크게 보여주세요','Hold the card text inside this guide'); dictionary.set('문화 카드 인식 완료','Cultural card recognized');
  dictionary.set('카메라를 준비하고 있습니다…','Preparing the camera…'); dictionary.set('한글 문자 인식기를 준비하고 있습니다…','Preparing Korean text recognition…');
  translate(document.body);
  new MutationObserver(records => records.forEach(record => record.addedNodes.forEach(translate))).observe(document.body, {childList:true, subtree:true});
})();
